# Generated by Django 4.0.1 on 2022-01-11 19:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ru', models.CharField(max_length=50)),
                ('first_name_az', models.CharField(max_length=50)),
                ('last_name_ru', models.CharField(max_length=50)),
                ('last_name_az', models.CharField(max_length=50)),
                ('designation_ru', models.CharField(max_length=100)),
                ('designation_az', models.CharField(max_length=100)),
                ('about_ru', ckeditor.fields.RichTextField()),
                ('about_az', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='team/%Y/%m/%d/')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
