# Generated by Django 4.0.1 on 2022-01-13 09:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title_ru', models.CharField(max_length=100, unique=True)),
                ('blog_title_az', models.CharField(max_length=100, unique=True)),
                ('blog_title_en', models.CharField(blank=True, max_length=100)),
                ('blog_brief_ru', models.CharField(blank=True, max_length=200, unique=True)),
                ('blog_brief_az', models.CharField(blank=True, max_length=200, unique=True)),
                ('blog_brief_en', models.CharField(blank=True, max_length=200)),
                ('blog_description_ru', ckeditor.fields.RichTextField()),
                ('blog_description_az', ckeditor.fields.RichTextField()),
                ('blog_description_en', ckeditor.fields.RichTextField(blank=True)),
                ('blog_photo', models.ImageField(upload_to='recipes/%Y/%m/%d/')),
                ('blog_photo_1', models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/')),
                ('blog_photo_2', models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/')),
                ('blog_photo_3', models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/')),
                ('blog_photo_4', models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/')),
                ('blog_photo_5', models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
