# Generated by Django 4.0.1 on 2022-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_recipe_brief_ru_recipe_ricipe_brief_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_brief_ru',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ricipe_brief_az',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ricipe_brief_en',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
