# Generated by Django 4.0.1 on 2022-01-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_recipe_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ricipe_brief_az',
            new_name='recipe_brief_az',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ricipe_brief_en',
            new_name='recipe_brief_en',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_photo_1',
            field=models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_photo_3',
            field=models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_photo_4',
            field=models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/'),
        ),
    ]
